CREATE USER 'blog2627'@'localhost' IDENTIFIED BY 'Blog2627$';

GRANT USAGE ON *.* TO 'blog2627'@'localhost';

ALTER USER 'blog2627'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON blog2627.* 
TO 'blog2627'@'localhost';

FLUSH PRIVILEGES;